version: '3'
services:
  app:
    build: ./dashboard
    ports:
      - "5000:5000"
    restart: always
  twitter-breaking-news:
    build: ./twitter-breaking-news
    ports:
      - "3000:3000"
    restart: always
    environment:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_AUTH_TOKEN
      - TWITTER_AUTH_SECRET
